Get menu item feature
jfoshee2/RestaurantWebApp pull request #22
Opened 2021-03-02 20:42 UTC by Fulgar

2021-03-04 23:04 UTC, jfoshee2 requested changes

2021-03-04 23:04 UTC, jfoshee2 commented on RestaurantWebApp/Controllers/WeatherForecastController.cs
> +    // [Route("[controller]")]
Remove dead code

2021-03-05 00:17 UTC, jfoshee2 approved these changes

2021-03-05 00:17 UTC, merged

2021-03-05 00:20 UTC, Fulgar commented
resolved